import { codeBlock, escapeHtml, icon, routeLabel, shell } from './ui.mjs'
import { skills } from './home.mjs'

export const docNavigation = [
  { slug: '', title: 'Bienvenue', group: 'DÉMARRER', icon: 'book' },
  { slug: 'installation', title: 'Installation', group: 'DÉMARRER', icon: 'terminal' },
  { slug: 'workflow', title: 'Votre première carte', group: 'COMPRENDRE', icon: 'branch' },
  { slug: 'routage', title: 'Complexité & modèles', group: 'COMPRENDRE', icon: 'grid' },
  { slug: 'agents', title: 'Agents & contextes', group: 'COMPRENDRE', icon: 'layers' },
  { slug: 'skills', title: 'Skills & commandes', group: 'RÉFÉRENCE', icon: 'code' },
  { slug: 'configuration', title: 'Configuration & update', group: 'RÉFÉRENCE', icon: 'refresh' },
]

function sources(context, paths) {
  return `<div class="source-links"><span>SOURCE DE VÉRITÉ</span>${paths.map((path) => `<a href="${context.repository}/blob/main/${path}">${escapeHtml(path)} ${icon('external')}</a>`).join('')}</div>`
}

function pages(context) {
  const u = (path) => `${context.basePath}${path}`
  const callout = (title, body) => `<aside class="callout"><strong>${title}</strong><p>${body}</p></aside>`
  const section = (id, title, body) => ({ id, title, body })
  return {
    '': {
      label: 'Démarrer', title: 'Une méthode pour vos agents.', description: 'De la préparation d’un ticket à son merge, chaque phase a une responsabilité, un contexte et un résultat attendu.',
      sections: [
        section('vue-ensemble', 'Le parcours, en un coup d’œil', `<p>Agentic Workflow organise la livraison d’une carte à la fois. Le hardening rend le ticket exécutable, puis l’orchestrateur fait travailler des agents spécialisés. Le niveau de risque détermine le modèle, le reasoning et le nombre de reviews.</p><div class="doc-flow">${['Cadrer', 'Classifier', 'Implémenter', 'Relire', 'Livrer'].map((label, i) => `<span><small>0${i + 1}</small>${label}</span>`).join('')}</div><p>Un finding entraîne un rework ciblé puis une nouvelle review. Un blocage réel revient à l’humain. Le workflow conserve son état dans Git, Linear et des checkpoints compacts.</p>`),
        section('par-ou-commencer', 'Le bon point de départ', `<div class="doc-card-grid"><a href="${u('/docs/installation/')}">${icon('terminal')}<h3>Installer le workflow</h3><p>Préparer votre repository et votre équipe Linear.</p><span>Commencer ${icon('arrow')}</span></a><a href="${u('/docs/workflow/')}">${icon('branch')}<h3>Livrer une première carte</h3><p>Suivre le parcours du ticket au merge confirmé.</p><span>Découvrir le parcours ${icon('arrow')}</span></a><a href="${u('/docs/routage/')}">${icon('grid')}<h3>Comprendre le routage</h3><p>Explorer les quatre niveaux et leurs reviews.</p><span>Voir les règles ${icon('arrow')}</span></a><a href="${u('/docs/skills/')}">${icon('code')}<h3>Consulter les skills</h3><p>Lire les entrées, sorties et limites de chaque phase.</p><span>Ouvrir la référence ${icon('arrow')}</span></a></div>`),
        section('prerequis', 'Ce dont vous avez besoin', `<ul><li>Un repository Git et <strong>Node.js 20 ou plus</strong>.</li><li>Le CLI Codex pour l’orchestration automatique.</li><li>Un accès Linear exposant les opérations sur les issues, commentaires, labels et relations.</li><li>Les modèles du routage disponibles sur votre hôte Codex.</li></ul>${callout('Claude Code', 'Les commandes Claude donnent accès aux mêmes contrats de phase. Le runner automatique de cette version utilise Codex ; il ne lance pas Claude.')}`),
      ], source: ['README.md', 'workflow/contracts/delivery.md'],
    },
    installation: {
      label: 'Démarrer', title: 'Installez. Configurez. Commencez.', description: 'La source officielle reste dans son propre dépôt. Chaque projet reçoit une copie gérée et une petite configuration qui lui appartient.',
      sections: [
        section('cloner', '1. Cloner la source', `${codeBlock(`git clone ${context.repository}.git\ncd agentic-workflow`)}<p>Pour un usage reproductible, vous pouvez choisir un tag de release existant. La version du workflow est déclarée dans <code>VERSION</code>.</p>`),
        section('installer', '2. Installer dans votre projet', `${codeBlock('./install.sh /chemin/vers/votre-projet')}<p>Le chemin doit désigner la racine d’un repository Git existant. L’installateur indique les fichiers créés, mis à jour et les conflits éventuels.</p><div class="table-scroll"><table><thead><tr><th>Emplacement</th><th>Ce qu’il contient</th></tr></thead><tbody><tr><td><code>.agents/skills/</code></td><td>Les skills canoniques</td></tr><tr><td><code>.codex/agents/</code></td><td>Les quatre agents Codex</td></tr><tr><td><code>.claude/commands/</code></td><td>Les commandes Claude Code</td></tr><tr><td><code>.agent-workflow/</code></td><td>Le runtime, les contrats et le manifest</td></tr><tr><td><code>agent-workflow.config.json</code></td><td>Votre configuration projet</td></tr></tbody></table></div><p>Si un conflit est signalé, comparez le fichier conservé à la version entrante indiquée par l’installateur avant de continuer.</p>`),
        section('linear', '3. Configurer l’équipe Linear', `<p>Dans le repository consommateur, renseignez votre équipe dans <code>agent-workflow.config.json</code>. Adaptez les statuts et labels si votre équipe emploie d’autres noms.</p>${codeBlock(JSON.stringify({ tracker: { provider: 'linear', team: 'Votre équipe' } }, null, 2), 'agent-workflow.config.json')}<p>Vérifiez que votre session dispose des outils de lecture et d’écriture d’issues. Les labels <code>hardened</code> et <code>ready-for-agent</code> doivent exister : le workflow ne les crée pas automatiquement.</p>${callout('Un projet prêt à travailler', 'Committez les fichiers installés et la configuration projet. Conservez vos règles métier dans AGENTS.md ou CLAUDE.md. Les secrets ne vont pas dans la configuration du workflow.')}`),
        section('premiere-carte', '4. Préparer une première carte', `<p>Dans une session agent ouverte sur le projet, invoquez le skill avec un identifiant réel :</p>${codeBlock('/harden-card PROJ-123', 'Dans votre assistant')}<p>Le hardening lit la carte et le code, propose les changements nécessaires et persiste le routage après validation. Continuez ensuite avec <a href="${u('/docs/workflow/')}">le guide de votre première carte</a>.</p>`),
      ], source: ['scripts/agent-workflow.mjs', 'workflow/templates/agent-workflow.config.json'],
    },
    workflow: {
      label: 'Comprendre', title: 'Du ticket au merge confirmé.', description: 'Une orchestration est toujours limitée à une carte, une branche, un worktree et une pull request.',
      sections: [
        section('harden', 'Préparer un ticket exécutable', `<p><code>/harden-card</code> vérifie le périmètre, les critères d’acceptation, les dépendances et les tests. Une ambiguïté bloquante demande une décision humaine avant l’exécution.</p><p>La classification et la route sont conservées dans un commentaire Linear marqué <code>delivery-routing:v1</code>. Le ticket doit être hardened, prêt pour un agent et sans bloqueur ouvert.</p>`),
        section('lancer', 'Lancer l’orchestrateur', `<p>Depuis le repository consommateur :</p>${codeBlock('node .agent-workflow/bin/run-card.mjs PROJ-123')}<p>Le runner ouvre un nouveau processus Codex. <code>/start-card</code> réconcilie l’état réel, prépare ou reprend le worktree et délègue les phases à des contextes neufs.</p>${codeBlock('node .agent-workflow/bin/run-card.mjs PROJ-123 --dry-run', 'Prévisualiser la commande sans lancer Codex')}`),
        section('reviews', 'Implémenter, relire, corriger', `<ol><li>L’implémenteur modifie le code, exécute les validations et retourne un commit.</li><li>Le ou les reviewers relisent ce commit et rendent un reçu lié à son SHA.</li><li>Les findings confirmés passent à un reworker dans un nouveau contexte.</li><li>Le nouveau commit fait l’objet d’une nouvelle review : les anciennes approbations ne valent plus.</li></ol><p>Par défaut, ${context.defaults.delivery.maxReworkCycles} cycles de rework sont autorisés. Des avis de review contradictoires sont soumis à l’humain.</p>`),
        section('terminer', 'Livrer et savoir s’arrêter', `<p>Le shipper reçoit les approbations pour le commit courant. Il vérifie les gates, la PR, la CI et le merge, puis les contrôles de déploiement demandés par le projet.</p><div class="state-grid"><span><strong>DONE</strong>Livraison confirmée</span><span><strong>NEEDS_HUMAN</strong>Décision ou preuve humaine</span><span><strong>FAILED</strong>Échec non récupérable</span></div><p>Ces états sont terminaux pour la carte. L’orchestration ne choisit pas automatiquement une autre tâche.</p>`),
        section('backlog', 'Parcourir un backlog', `<p>La boucle externe démarre un processus neuf pour chaque carte éligible. Elle s’arrête à la première carte nécessitant une intervention, ou à la limite demandée.</p>${codeBlock('node .agent-workflow/bin/backlog-loop.mjs --max-cards 3')}<p>Elle nécessite une équipe Linear configurée et des cartes déjà durcies. Les sorties locales se trouvent dans <code>.delivery/</code>, ignoré par Git.</p>`),
      ], source: ['workflow/skills/start-card/SKILL.md', 'workflow/contracts/delivery.md'],
    },
    routage: {
      label: 'Comprendre', title: 'La rigueur suit le risque.', description: 'La classification est établie à partir du ticket et du code. La table ci-dessous est générée depuis les routes exécutables du workflow.',
      sections: [
        section('niveaux', 'Quatre niveaux, des routes explicites', `<div class="table-scroll"><table><thead><tr><th>Niveau</th><th>Implémentation</th><th>Review indépendante</th></tr></thead><tbody>${Object.entries(context.routes).map(([name, route]) => `<tr><td><span class="level-chip">${name}</span></td><td>${routeLabel(route.implementation)}${name === 'complex' ? '<small class="table-note">high selon l’effort requis</small>' : ''}</td><td>${route.reviewers.map(routeLabel).join('<br>')}</td></tr>`).join('')}</tbody></table></div><p>Les modèles exacts et les routes fixes sont également accessibles dans le runtime installé :</p>${codeBlock('node .agent-workflow/bin/agent-workflow.mjs routes')}`),
        section('critique', 'Les contrats sensibles passent en critical', `<p>Le hardening commence par chercher un risque sensible ou irréversible : autorisations, paiements, migrations destructrices, confidentialité, intégrité des données, infrastructure de production ou secrets.</p><p>Il doit citer le contrat changé et un mode de défaillance plausible. Toucher un fichier voisin ne suffit pas à justifier un override.</p>`),
        section('score', 'Sinon, huit dimensions documentées', `<div class="table-scroll"><table><thead><tr><th>Dimension</th><th>Score</th></tr></thead><tbody>${[['Surface du changement et nombre de couches', '0–3'], ['Complexité de la logique métier', '0–3'], ['Dépendances externes', '0–2'], ['Asynchrone, concurrence, retries, ordre', '0–2'], ['Risque de régression', '0–3'], ['Difficulté de test', '0–2'], ['Ambiguïté restante', '0–2'], ['Étendue de l’impact', '0–3']].map(([dimension, range]) => `<tr><td>${dimension}</td><td>${range}</td></tr>`).join('')}</tbody></table></div><p>Le score donne <strong>simple de 0 à 4</strong>, <strong>standard de 5 à 10</strong> et <strong>complex de 11 à 20</strong>. Une ambiguïté bloquante interrompt le hardening ; elle n’est pas dissimulée dans un score plus élevé.</p>`),
        section('reasoning', 'Reasoning, rework et escalade', `<p>Pour complex, l’implémentation utilise <code>high</code> dès 15 points, ou si l’ambiguïté, la difficulté de test ou le risque de régression atteint 2. Le rework reprend la route d’implémentation.</p><p>Un blocage répété avec le même fingerprint permet une escalade vers Sol / high. Les routes déjà en Sol / high n’ont pas d’escalade automatique supplémentaire.</p><p>L’orchestrateur et le shipper utilisent ${routeLabel(context.fixed.orchestrator)}. Le sélecteur de backlog utilise ${routeLabel(context.fixed.backlogSelector)}.</p>${callout('Disponibilité des modèles', 'Ce sont les routes configurées dans cette version. Vérifiez que ces identifiants sont disponibles sur votre hôte avant de lancer la livraison.')}`),
      ], source: ['workflow/config/defaults.mjs', 'workflow/orchestrator/delivery-state.mjs'],
    },
    agents: {
      label: 'Comprendre', title: 'Des rôles séparés. Un cap commun.', description: 'Les agents se transmettent des faits structurés. La séparation des contextes protège l’indépendance de la review.',
      sections: [
        section('roles', 'Les quatre agents de livraison', `<div class="agent-reference">${[
          ['implementer', 'Implémenter', 'Reçoit le ticket, le worktree, la branche, le SHA de base et sa route. Retourne un commit et les validations.'],
          ['reviewer', 'Relire', 'Reçoit le ticket, le worktree, les SHAs base/head et un slot. Lit le code sans le modifier et rend un reçu structuré.'],
          ['reworker', 'Corriger', 'Reçoit le commit relu et les findings confirmés. Produit les corrections minimales, de nouvelles validations et un nouveau commit.'],
          ['shipper', 'Livrer', 'Reçoit le commit approuvé et les reçus correspondants. Prend en charge la PR, la CI, le merge et les preuves de livraison.'],
        ].map(([agent, label, description]) => `<article><code>${agent}</code><h3>${label}</h3><p>${description}</p></article>`).join('')}</div>`),
        section('contextes', 'Ce qui traverse un passage de relais', `<p>Le ticket, les instructions du projet et l’état Git sont consultés directement. Le reviewer ne reçoit pas la conversation d’implémentation, ses justifications ni les conclusions d’un autre reviewer.</p><p>En critical, les reviewers A et B travaillent sur le même commit, avec des modèles distincts. Un désaccord n’est pas tranché arbitrairement par l’orchestrateur.</p>${codeBlock('card: PROJ-123\nstatus: approved\nreviewed_head: <sha>\nreviewer_slot: single\nfindings: []', 'Exemple de reçu de review')}`),
        section('memoire', 'La mémoire reste dans les preuves', `<p>Git et les commentaires marqués de Linear conservent la route, les checkpoints et les reçus. Le fichier <code>.delivery/state/&lt;CARD&gt;.json</code> sert à la récupération locale.</p><p>À la reprise, le workflow confronte les checkpoints aux branches, commits, PR et checks actuels. Une ancienne approbation ne peut pas valider un nouveau commit.</p>`),
      ], source: ['workflow/agents/codex', 'workflow/contracts/delivery.md'],
    },
    skills: {
      label: 'Référence', title: 'Six commandes, un même contrat.', description: 'Chaque skill possède un périmètre défini et une condition de fin. Les adaptateurs Claude Code lisent les mêmes fichiers canoniques.',
      sections: skills.map((skill) => section(skill.name, `/${skill.name}`, `<p class="skill-doc-lead">${skill.title}</p><p>${skill.description}</p>${codeBlock(skill.name === 'code-review' ? '/code-review PROJ-123, base <sha>, head <sha>, slot single' : skill.name === 'rework' ? '/rework PROJ-123 at <sha> using <structured findings>' : skill.name === 'implement' ? '/implement PROJ-123 in <worktree>, base <sha>, route <model/reasoning>' : skill.name === 'ship-production-change' ? '/ship-production-change PROJ-123 at approved head <sha>' : `/${skill.name} PROJ-123`, 'Commande')}<a class="source-skill" href="${context.repository}/blob/main/workflow/skills/${skill.name}/SKILL.md">Lire le contrat complet ${icon('external')}</a>${skill.name === 'harden-card' ? '<p>L’alias historique <code>/harden-project-cards</code> pointe vers ce même contrat. Le hardening propose les modifications avant de les appliquer, sauf autorisation explicite préalable.</p>' : ''}`)),
      source: ['workflow/skills', 'workflow/commands/claude'],
    },
    configuration: {
      label: 'Référence', title: 'Votre projet garde ses réglages.', description: 'Le moteur est partagé. Les conventions du projet et les paramètres de votre machine restent dans leurs propres fichiers.',
      sections: [
        section('couches', 'Trois couches de configuration', `<ol><li><strong>Défauts du workflow</strong> — versionnés dans la source centrale.</li><li><strong>Projet</strong> — <code>agent-workflow.config.json</code>, committé dans le repository consommateur.</li><li><strong>Machine</strong> — <code>.agent-workflow.local.json</code>, prioritaire et gitignoré.</li></ol><p>Le workflow détecte la branche de base, le gestionnaire de paquets et les scripts habituels. Configurez une valeur explicite quand cette détection ne correspond pas à votre projet.</p>${codeBlock(JSON.stringify({ tracker: { team: 'Votre équipe' }, git: { baseBranch: 'auto' }, commands: { install: 'auto', fullCheck: 'npm run check' } }, null, 2), 'Configuration minimale personnalisée')}`),
        section('verification', 'Consulter la configuration effective', `${codeBlock('node .agent-workflow/bin/agent-workflow.mjs config')}<p>La commande s’exécute depuis la racine du projet et fusionne les trois couches. Le détail des options est disponible dans le <a href="${context.repository}/blob/main/docs/CONFIGURATION.md">guide de configuration du repository</a>.</p>`),
        section('update', 'Mettre à jour un projet', `<p>Dans votre clone de la source officielle :</p>${codeBlock('git pull --rebase\n./update.sh /chemin/vers/votre-projet')}<p>Le manifest compare les checksums actuels, ceux de la dernière installation et ceux de la version entrante. La configuration du projet n’est pas remplacée.</p>`),
        section('conflits', 'Résoudre un conflit explicitement', `<p>Un fichier géré modifié manuellement reste en place. La version entrante est enregistrée dans <code>.agent-workflow/conflicts/</code> et la commande retourne le code 2.</p><ol><li>Comparez le fichier local et le chemin <code>incoming</code> indiqué par le manifest.</li><li>Décidez des changements à conserver.</li><li>Relancez l’update. Un fichier identique à la version entrante est à nouveau reconnu comme géré.</li></ol><p>Les fichiers gérés devenus obsolètes et restés intacts sont déplacés dans <code>.agent-workflow/backups/</code>.</p>${callout('Les secrets restent locaux', 'L’installateur ne copie ni .env ni identifiants. La configuration environment.copyFiles décrit uniquement les noms des fichiers autorisés dans les worktrees de livraison ; leur contenu reste hors de la source officielle.')}`),
      ], source: ['docs/CONFIGURATION.md', 'docs/MANAGED-FILES.md'],
    },
  }
}

export function docsPage(slug, context) {
  const page = pages(context)[slug]
  const index = docNavigation.findIndex((entry) => entry.slug === slug)
  const u = (path) => `${context.basePath}${path}`
  let previousGroup = ''
  const nav = docNavigation.map((entry) => {
    const heading = previousGroup === entry.group ? '' : `<p class="sidebar-group">${entry.group}</p>`
    previousGroup = entry.group
    return `${heading}<a ${entry.slug === slug ? 'aria-current="page"' : ''} href="${u(`/docs/${entry.slug ? `${entry.slug}/` : ''}`)}">${icon(entry.icon)}${entry.title}</a>`
  }).join('')
  const neighbor = (entry, direction) => entry ? `<a href="${u(`/docs/${entry.slug ? `${entry.slug}/` : ''}`)}"><small>${direction}</small><strong>${entry.title} ${icon('arrow')}</strong></a>` : '<span></span>'
  const content = `<main id="main" class="docs-layout page-width"><aside class="docs-sidebar"><div class="docs-sidebar-label">LA DOCUMENTATION <span>v${escapeHtml(context.version)}</span></div><nav aria-label="Chapitres de la documentation">${nav}</nav><div class="sidebar-github">${icon('github')}<p>Un workflow ouvert.<br>Des contributions bienvenues.</p><a href="${context.repository}">Explorer le repository ${icon('external')}</a></div></aside><article class="doc-article"><div class="breadcrumb"><a href="${u('/docs/')}">Documentation</a><span>/</span><span>${page.label}</span></div><h1>${page.title}</h1><p class="doc-description">${page.description}</p><div class="mobile-toc"><details><summary>Sur cette page</summary><nav aria-label="Sommaire mobile">${page.sections.map((s) => `<a href="#${s.id}">${s.title}</a>`).join('')}</nav></details></div>${page.sections.map((s) => `<section id="${s.id}" class="doc-section"><h2>${s.title}</h2>${s.body}</section>`).join('')}${sources(context, page.source)}<nav class="doc-pagination" aria-label="Pages voisines">${neighbor(docNavigation[index - 1], 'PRÉCÉDENT')}${neighbor(docNavigation[index + 1], 'À SUIVRE')}</nav></article><aside class="docs-toc"><span>SUR CETTE PAGE</span><nav aria-label="Sommaire">${page.sections.map((s) => `<a href="#${s.id}">${s.title}</a>`).join('')}</nav></aside></main>`
  return shell({ title: `${docNavigation[index].title} — Agentic Workflow`, description: page.description, content, context, active: `docs${slug ? `/${slug}` : ''}` })
}
