import { codeBlock, escapeHtml, icon, mark, routeLabel, shell } from './ui.mjs'

export const skills = [
  { name: 'harden-card', number: '01', phase: 'CADRER', title: 'Un ticket prêt à être exécuté.', description: 'Challenger le périmètre, lever les ambiguïtés et choisir le niveau de complexité.', icon: 'grid' },
  { name: 'start-card', number: '02', phase: 'ORCHESTRER', title: 'Une carte. Un parcours complet.', description: 'Préparer le worktree, router les agents et reprendre à partir de preuves durables.', icon: 'branch' },
  { name: 'implement', number: '03', phase: 'CONSTRUIRE', title: 'Le bon agent, au bon endroit.', description: 'Implémenter le ticket dans un contexte neuf, tester et produire un commit.', icon: 'code' },
  { name: 'code-review', number: '04', phase: 'VÉRIFIER', title: 'Un regard vraiment indépendant.', description: 'Relire les exigences et le code sans hériter des conclusions de l’implémentation.', icon: 'review' },
  { name: 'rework', number: '05', phase: 'CORRIGER', title: 'Des corrections qui restent ciblées.', description: 'Traiter les findings confirmés, puis passer une nouvelle review sur le nouveau commit.', icon: 'refresh' },
  { name: 'ship-production-change', number: '06', phase: 'LIVRER', title: 'Terminer avec des preuves.', description: 'Vérifier la CI, la PR, le merge et les validations de déploiement requises.', icon: 'check' },
]

const levels = {
  simple: { label: 'Simple', score: '0–4 points', example: 'Ajuster une validation locale.', description: 'Un changement circonscrit, testable indépendamment, avec une review proportionnée.' },
  standard: { label: 'Standard', score: '5–10 points', example: 'Faire évoluer un parcours utilisateur.', description: 'Plusieurs fichiers ou couches, un raisonnement renforcé et une review indépendante.' },
  complex: { label: 'Complex', score: '11–20 points', example: 'Refondre un traitement asynchrone.', description: 'Un périmètre large ou couplé. L’effort passe à high dès 15 points, ou selon les dimensions de risque.' },
  critical: { label: 'Critical', score: 'Contrat sensible', example: 'Modifier les autorisations d’accès.', description: 'Sécurité, paiements ou données sensibles : deux reviewers indépendants, avec deux modèles distincts.' },
}

export function homePage(context) {
  const u = (path) => `${context.basePath}${path}`
  const content = `<main id="main">
<section class="hero page-width">
<div class="eyebrow hero-eyebrow"><span class="status-dot"></span> UNE MÉTHODE OPEN SOURCE POUR L’AGENTIC CODING <span class="version-pill">v${escapeHtml(context.version)}</span></div>
<h1>Vos agents codent.<br>Gardez <em>le fil.</em></h1>
<p class="hero-description">Transformez un ticket en code relu et livré.<br>Des agents spécialisés, des contextes neufs et une rigueur<br class="desktop-break"> qui s’adapte au risque de chaque changement.</p>
<div class="hero-actions"><a class="button button-accent" href="${u('/docs/installation/')}">Installer le workflow ${icon('arrow')}</a><a class="text-link" href="#methode">Comprendre la méthode <span>↓</span></a></div>
<div class="hero-compatibility"><span>${icon('terminal')} Codex</span><span>${icon('code')} Claude Code <small>commandes</small></span><span>${icon('branch')} Votre repository</span></div>
<div class="workflow-canvas" aria-label="Schéma du workflow : cadrer, implémenter, relire et livrer">
<div class="canvas-heading"><span class="mini-label"><span class="status-dot"></span> UNE CARTE, DU DÉBUT À LA FIN</span><span class="canvas-caption">Le contexte change. Le cap reste.</span></div>
<div class="diagram-flow">
<div class="flow-node"><div class="flow-icon">${icon('grid')}</div><span class="flow-number">01 / HARDEN</span><h3>Cadrer</h3><p>Un ticket explicite.<br>Un risque évalué.</p><span class="node-token">ready-for-agent</span></div>
<span class="flow-arrow">${icon('arrow')}</span>
<div class="flow-node"><div class="flow-icon">${icon('code')}</div><span class="flow-number">02 / IMPLEMENT</span><h3>Construire</h3><p>Un agent dédié.<br>Un worktree isolé.</p><span class="node-token">contexte neuf</span></div>
<span class="flow-arrow">${icon('arrow')}</span>
<div class="flow-node review-node"><div class="flow-icon">${icon('review')}</div><span class="flow-number">03 / REVIEW</span><h3>Vérifier</h3><p>Un regard indépendant.<br>Le commit exact.</p><span class="node-token">1 ou 2 reviews</span></div>
<span class="flow-arrow">${icon('arrow')}</span>
<div class="flow-node ship-node"><div class="flow-icon">${icon('check')}</div><span class="flow-number">04 / SHIP</span><h3>Livrer</h3><p>Les gates au vert.<br>Le merge confirmé.</p><span class="node-token">DONE ${icon('check')}</span></div>
</div>
<div class="rework-loop"><span></span><p>${icon('refresh')} Un finding ? Un rework ciblé, puis une nouvelle review.</p><span></span></div>
<div class="canvas-footer"><span>01 carte</span><span>01 branche</span><span>01 pull request</span><span class="footer-proof">${icon('lock')} Des preuves à chaque passage</span></div>
</div>
</section>
<section class="manifesto page-width" id="methode"><div class="eyebrow">01 — LA MÉTHODE</div><div class="section-split"><h2>Coder plus vite.<br><em>Livrer avec confiance.</em></h2><p>Les agents savent produire du code. Le workflow leur donne un cadre : un périmètre clair, une responsabilité par phase et une vérification avant chaque passage de relais.</p></div>
<div class="principles"><article><span class="principle-icon">${icon('layers')}</span><h3>Un contexte neuf.<br>À chaque étape.</h3><p>Le reviewer lit le ticket et le diff. Il ne reçoit ni la conversation ni les conclusions de l’implémenteur.</p><span class="tiny-label">INDÉPENDANCE PAR CONSTRUCTION</span></article><article><span class="principle-icon">${icon('branch')}</span><h3>La bonne rigueur.<br>Pour le bon risque.</h3><p>Un ajustement local et une migration sensible n’ont pas le même parcours. Modèle, effort et reviews suivent la classification.</p><span class="tiny-label">QUATRE NIVEAUX DE COMPLEXITÉ</span></article><article><span class="principle-icon">${icon('lock')}</span><h3>Des preuves.<br>Pas des suppositions.</h3><p>Tests, commits et reçus de review gardent la mémoire du travail. Le workflow reprend depuis l’état réel du repository.</p><span class="tiny-label">DES PASSAGES DE RELAIS EXPLICITES</span></article></div>
</section>
<section class="routing-section" id="routage"><div class="page-width"><div class="routing-heading"><div><div class="eyebrow">02 — UNE RIGUEUR ADAPTATIVE</div><h2>Chaque changement<br>a son <em>parcours.</em></h2></div><p>Choisissez un niveau pour explorer le routage.<br>Les modèles ci-dessous viennent directement<br>de la configuration du workflow.</p></div>
<div class="routing-demo"><div class="risk-tabs" role="tablist" aria-label="Niveau de complexité">${Object.entries(levels).map(([key, level], index) => `<button id="tab-${key}" type="button" role="tab" aria-controls="panel-${key}" aria-selected="${index === 1}" tabindex="${index === 1 ? '0' : '-1'}" data-risk="${key}"><span class="risk-dot risk-${key}"></span>${level.label}<span class="risk-index">0${index + 1}</span></button>`).join('')}</div>
${Object.entries(levels).map(([key, level], index) => { const route = context.routes[key]; return `<div id="panel-${key}" role="tabpanel" aria-labelledby="tab-${key}" class="route-panel" ${index === 1 ? '' : 'hidden'}><div class="route-scenario"><span class="score-label">${level.score}</span><h3>${level.example}</h3><p>${level.description}</p><a href="${u('/docs/routage/')}">Les critères de classification ${icon('arrow')}</a></div><div class="route-stages"><div class="route-stage"><span class="route-stage-icon">${icon('code')}</span><div><small>IMPLÉMENTATION</small><strong>${routeLabel(route.implementation)}</strong><code>${escapeHtml(route.implementation.model)}</code></div><span class="fresh-label">Contexte neuf</span></div><div class="route-connector"></div>${route.reviewers.map((reviewer, i) => `<div class="route-stage"><span class="route-stage-icon">${icon('review')}</span><div><small>REVIEW ${route.reviewers.length > 1 ? (i === 0 ? 'A' : 'B') : 'INDÉPENDANTE'}</small><strong>${routeLabel(reviewer)}</strong><code>${escapeHtml(reviewer.model)}</code></div><span class="fresh-label">${route.reviewers.length > 1 ? 'Indépendante' : 'Contexte neuf'}</span></div>`).join('')}<div class="route-outcome">${icon('check')} ${route.reviewers.length === 2 ? 'Deux approbations indépendantes requises' : 'Une approbation requise'} sur le commit courant</div></div></div>` }).join('')}
</div><p class="routing-note"><span>Le risque ne se devine pas.</span> Le hardening documente les critères et conserve la route dans le ticket.</p>
</div></section>
<section class="skills-section page-width" id="skills"><div class="eyebrow">03 — LA BOÎTE À OUTILS</div><div class="section-split"><h2>Une commande.<br><em>Une responsabilité.</em></h2><p>Des skills lisibles et versionnés, qui partagent les mêmes contrats. Explorez chaque phase, de la préparation du ticket à la livraison.</p></div><div class="skill-grid">${skills.map((skill) => `<a class="skill-card" href="${u(`/docs/skills/#${skill.name}`)}"><div class="skill-top"><span>${skill.number} / ${skill.phase}</span>${icon(skill.icon)}</div><code>/${skill.name}</code><h3>${skill.title}</h3><p>${skill.description}</p><span class="skill-link">Explorer le skill ${icon('arrow')}</span></a>`).join('')}</div><p class="alias-note">Vous utilisez déjà <code>/harden-project-cards</code> ? Cet alias reste disponible.</p></section>
<section class="install-section page-width" id="installation"><div class="install-copy"><div class="eyebrow">04 — À VOUS DE JOUER</div><h2>Votre prochaine PR<br>commence <em>ici.</em></h2><p>Clonez la source, installez dans votre repository et configurez votre équipe Linear. Le workflow vous appartient.</p><a class="button button-accent" href="${u('/docs/installation/')}">Suivre le guide d’installation ${icon('arrow')}</a><div class="install-requirements"><span>${icon('check')} Node.js 20+</span><span>${icon('check')} Git</span><span>${icon('check')} Linear</span></div></div><div class="install-terminal"><div class="terminal-title"><span class="terminal-dots"><i></i><i></i><i></i></span><span>un nouveau départ</span><span>~/projects</span></div>${codeBlock(`git clone ${context.repository}.git\ncd agentic-workflow\n./install.sh /chemin/vers/votre-projet`, 'Installer') }<div class="terminal-result"><span>${icon('check')} Des fichiers gérés, des réglages préservés.</span><p>L’update détecte les modifications manuelles et signale les conflits.</p></div></div></section>
<section class="faq-section page-width"><div><div class="eyebrow">QUELQUES REPÈRES</div><h2>Avant de<br><em>vous lancer.</em></h2></div><div class="faq-list"><details><summary>Est-ce compatible avec mon projet ?<span>+</span></summary><p>Le workflow est indépendant de votre stack. L’installation demande un repository Git et Node.js 20+. Les commandes de validation sont détectées ou configurées dans votre projet.</p></details><details><summary>Codex et Claude Code ont-ils les mêmes capacités ?<span>+</span></summary><p>L’orchestration automatique et la boucle de backlog utilisent le CLI Codex. Claude Code dispose de commandes donnant accès aux mêmes contrats de phase. Les modèles routés doivent être disponibles sur votre hôte.</p></details><details><summary>Mes fichiers seront-ils écrasés lors d’un update ?<span>+</span></summary><p>Les fichiers gérés restés intacts sont mis à jour. Un fichier modifié manuellement est préservé et signalé en conflit. La configuration du projet et la configuration locale restent séparées.</p></details><details><summary>Est-ce gratuit ?<span>+</span></summary><p>Le workflow est open source sous licence MIT. L’utilisation des modèles, de votre assistant et des services connectés reste soumise à leurs propres conditions et coûts.</p></details></div></section>
<div class="closing-note page-width"><span class="closing-mark">${mark}</span><p>Gardez votre jugement.<br>Donnez une méthode à vos agents.</p><a href="${context.repository}">Lire le code ${icon('external')}</a></div>
</main>`
  return shell({ title: 'Agentic Workflow — Vos agents codent. Gardez le fil.', description: 'Une méthode open source pour passer du ticket au code relu et livré : agents spécialisés, contextes neufs et reviews adaptées au risque.', content, context, isHome: true })
}
